<?php
session_start();
require 'connection.php';

if (isset($_POST["submit"])) {
    $email = mysqli_real_escape_string($conn, $_POST["email"]);
    
    // Check if the email exists in the database
    $query = "SELECT * FROM tb_user WHERE email='$email'";
    $result = mysqli_query($conn, $query);
    
    if ($result && mysqli_num_rows($result) > 0) {
        $row = mysqli_fetch_assoc($result);
        
        // Generate a new random password (you can use a more secure method)
        $newPassword = generateRandomPassword(); // Implement this function
        
        // Update the user's password in the database
        $hashedPassword = password_hash($newPassword, PASSWORD_DEFAULT);
        $updateQuery = "UPDATE tb_user SET password='$hashedPassword' WHERE email='$email'";
        $updateResult = mysqli_query($conn, $updateQuery);
        
        if ($updateResult) {
            // Send the new password to the user's email
            $to = $email;
            $subject = "Password Reset";
            $message = "Your new password is (This is automatically generated by the website, and password standards do not apply). " . $newPassword; // You may want to provide instructions to change the password after login.
            $headers = "From: articlesharinggroup@gmail.com"; // Change this to your email address

            if (mail($to, $subject, $message, $headers)) {
                echo "<script>alert('Password reset successful. Check your email for the new password.');</script>";
            } else {
                echo "<script>alert('Failed to send the new password.');</script>";
            }
        } else {
            echo "<script>alert('Failed to update the password.');</script>";
        }
    } else {
        echo "<script>alert('Email not found in our records.');</script>";
    }
}

// Function to generate a random password
function generateRandomPassword($length = 8) {
    $characters = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
    $password = '';
    for ($i = 0; $i < $length; $i++) {
        $password .= $characters[rand(0, strlen($characters) - 1)];
    }
    return $password;
}
?>
<!DOCTYPE html>
<html>
   <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.2.1/css/fontawesome.min.css" integrity="sha384-QYIZto+st3yW+o8+5OHfT6S482Zsvz2WfOzpFSXMF9zqeLcFV0/wlZpMtyFcZALm" crossorigin="anonymous">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
      <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
      <link rel="preconnect" href="https://fonts.gstatic.com">
      <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@700&display=swap" rel="">
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link rel="icon" href="icon1.png" type="images/x-icon"/>
      <link rel="shortcut" href="icon1.png" type="images/x-icon"/>
      
      <link href="https://fonts.googleapis.com/css2?family=Peddana&family=Poppins:wght@400;500&family=Roboto:wght@700&display=swap" rel="stylesheet">
      
      <title>Forgot password</title>
      <style>
         * {
         padding: 0;
         margin: 0;
         top:0;
         font-family: "Poppins", sans-serif;
         }
         :root {
         --gradient-color: linear-gradient(rgb(230, 16, 201), #ccc);
         --background-color: #279EFF;
         --primary-color: #FFF;
         --text-color:black
         --sub-text:red;
         }
         body{
         background-color:#102C57;
         }
         nav {
         width: 100%;
         height: 100%;
         display: flex;
         background-color: var(--primary-color);
         top: 0;
         left: 0;
         position: sticky;
         z-index: 1;
         color:red;
         }
         .logo_nav h1{
         line-height:100px;
         margin-left:3rem;
         }
         .logo_nav img{
         width:40%;
         max-height: 500px;
         margin-top:0px;
         padding-top:0;
         }
         .items{
         display:flex;
         list-style:none;
         width:50%;
         height:8vh;
         justify-content:space-around;
         flex-direction:row;
         padding-top:2rem;
         }
         .items li a{
         text-decoration:none;
         color:red;
         font-weight:bolder;
         }
         .font{
         text-align:center;
         font-weight:bolder;
         font-size:3rem;
         padding-top:2rem;
         background:var(--text-color);
         -webkit-background-clip:text;
         -webkit-text-fill-color:transparent;
         }
         .font h1{
         padding-top:5rem;
         }
         h4{
         text-justify:newspaper;
         }
         .font h3{
         font-weight: bolder;
         font-size: 2.5rem;
         text-align: center;
         padding-top: 2rem;
         background: var(--gradient-color);
         -webkit-background-clip: text;
         -webkit-text-fill-color:transparent;
         text-transform: uppercase;
         }
         .font h5{
         font-weight: bolder;
         font-family: 'Courier New', Courier, monospace;
         font-size: 1.5rem;
         text-align: center;
         padding-top: 2rem;
         text-justify: distribute-all-lines;
         text-transform: uppercase;
         }
         /* /hero section */
         #hero{
         height:35rem;
         background-color:#C51605;
         }
         /* about section */
         #about-img{
         width:35rem;
         height:25rem;
         border-radius:10px;
         }
         .about-heading{
         padding-top:10rem;
         padding-bottom: 10rem;
         }
         .about-body{
         display: flex;
         justify-content: space-between;
         padding-right: 2rem;
         padding-left:2rem;
         }
         .about-content{
         padding-left: 3rem;
         padding-right:3rem;
         }
         /* 
         services section */
         .service-heading{
         padding-top:10rem;
         padding-bottom: 10rem;
         }
         .services{
         display: grid;
         justify-content: space-around;
         grid-template-columns: repeat(3,1fr);
         grid-gap: 2rem;
         padding-left :2rem;
         padding-right: 2rem ;
         padding-bottom: 5rem;
         }
         /* article section css */
         .article-img1{
         width:30rem;
         height:15rem;
         border-radius:10px;
         }
         .article-heading{
         padding-top:10rem;
         padding-bottom: 10rem;
         }
         .article-1{
         display: grid;
         grid-template-columns: 1fr 1.5fr;
         grid-template-rows: 0.5fr 0.5fr;
         grid-row-gap: 1rem;
         grid-column-gap: 5rem;
         justify-content: space-between;
         padding-left:3rem;
         padding-right:3rem;
         }
         .article-2{
         display: grid;
         grid-template-columns: 1.5fr 1fr;
         grid-template-rows: 0.5fr 0.5fr;
         grid-row-gap: 1rem;
         grid-column-gap: 5rem;
         justify-content: space-between;
         padding-left:3rem;
         }
         .article-3{
         display: grid;
         grid-template-columns: 1fr 1.5fr;
         grid-template-rows: 0.5fr 0.5fr;
         grid-row-gap: 1rem;
         grid-column-gap: 5rem;
         justify-content: space-between;
         padding-left:3rem;
         padding-right:3rem;
         }
         .footer-heading{
         padding-top: 2rem;
         padding-bottom: 5rem;
         }
         .footer-body{
         display: flex;
         justify-content: space-around;
         padding-bottom: 10rem;
         }
         /*#splashscreen{*/
         /*    height:700px;*/
         /*    background-color:#F8F0E5;*/
         /*    border-radius:10px;*/
         /*    align-items:center;*/
         /*    justify-content:center;*/
         /*    text-align:center;*/
         /*    margin-left:auto;*/
         /*    margin-top:auto;*/
         /*    margin-right:auto;*/
         /*    margin-bottom:auto;*/
         #splashscreen{
         /*background-color:#F8F0E5;*/
         position:fixed;
         width:100%;
         height:100%;
         opacity:0;
         animation:fade-out 4s;
         }
         #splashscreen img{
         --size:10px;
         position:absolute;
         top:50%;
         left:50%;
         transform:translate(-50%,-50%);
         width:var(--size);
         animation:zoom-in 2s;
         animation-delay: 2s;
         }
         @keyframes zoom-in{
         50%{
         width:var(--size);
         }
         60%{
         width:calc(var(--size)*0.9);
         }
         100%{
         width:150%;
         }
         }
         @keyframes fade-out{
         0%,85%{
         opacity:1;
         }
         100%{
         opacity:0;
         }
         }
         /*  #hero_content{*/
         /*     background-color:#C51605;*/
         /*     border-radius:10px;*/
         /*     color:white;*/
         /*     width:50%;*/
         /*     text-align:center;*/
         /*     align-items:center;*/
         /*     justify-content:center;*/
         /*     display:flex;*/
         /*     margin-left:auto;*/
         /*      margin-right:auto;*/
         /*      margin-top:auto;*/
         /*       margin-bottom:auto;*/
         /*  }*/
         /*  .Login_content*/
         /*  {*/
         /*       text-align:center;*/
         /*     align-items:center;*/
         /*     justify-content:center;*/
         /*  }*/
         /* .Login_content input[type=text]{*/
         /*     border-radius:10px;*/
         /*     border:none;*/
         /*     outline:none;*/
         /*     padding-left:5px;*/
         /*     font-size:20px;*/
         /*     margin-top:10px;*/
         /* }*/
         /*  .Login_content input[type=email]{*/
         /*     border-radius:10px;*/
         /*      border:none;*/
         /*     outline:none;*/
         /*     padding-left:5px;*/
         /*       font-size:20px;*/
         /*              margin-top:10px;*/
         /* }*/
         /*.Login_content input[type=password]{*/
         /*     border-radius:10px;*/
         /*      border:none;*/
         /*     outline:none;*/
         /*     padding-left:5px;*/
         /*     font-size:20px;*/
         /*     margin-top:10px;*/
         /* }*/
         /*#hero_content {*/
         /*    text-align: center;*/
         /*    padding: 20px;*/
         /*          background-color:#C51605;*/
         /*      border-radius:10px;*/
         /*      color:white;*/
         /*      width:50%;*/
         /*      text-align:center;*/
         /*      align-items:center;*/
         /*      justify-content:center;*/
         /*      display:flex;*/
         /*      margin-left:auto;*/
         /*       margin-right:auto;*/
         /*       margin-top:auto;*/
         /*        margin-bottom:auto;*/
         /*}*/
         /*.login_content {*/
         /*    border: 1px solid #ccc;*/
         /*    padding: 20px;*/
         /*    max-width: 100px;*/
         /*    margin: 0 auto;*/
         /*    border-radius: 5px;*/
         /*    box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);*/
         /*}*/
         /*h1 {*/
         /*    margin-bottom: 20px;*/
         /*}*/
         /*label {*/
         /*    display: block;*/
         /*    margin-bottom: 5px;*/
         /*    font-weight: bold;*/
         /*}*/
         /*input[type="text"],*/
         /*input[type="email"],*/
         /*input[type="password"] {*/
         /*        display: inline-block;*/
         /*    width: 105%;*/
         /*    padding: 10px;*/
         /*    margin-bottom: 10px;*/
         /*    border: 1px solid #ccc;*/
         /*    border-radius: 3px;*/
         /*}*/
         /*input[type="submit"] {*/
         /*    background-color: #007bff;*/
         /*    color: white;*/
         /*    padding: 10px 20px;*/
         /*    border: none;*/
         /*    border-radius: 3px;*/
         /*    cursor: pointer;*/
         /*}*/
         /*input[type="submit"]:hover {*/
         /*    background-color: #0056b3;*/
         /*}*/
         #hero_content {
         text-align: center;
         padding: 20px;
         /*float:right;*/
         }
         .login_content {
         padding: 20px;
         max-width: 500px;
         margin: 0 auto;
         border-radius: 10px;
         box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
         background-color:#102C57;
         }
         h1 {
         margin-bottom: 20px;
         color:white;
         }
         .input_container {
         position: relative;
         margin-bottom: 10px;
         }
         .icon_input {
         display: flex;
         align-items: center;
         color:white;
         }
         .icon_input i {
         margin-right: 10px;
         color: #fff;
         }
         input[type="text"],
         input[type="email"],
         input[type="password"] {
         width: 100%;
         padding: 10px;
         border: 1px solid #ccc;
         border-radius: 3px;
         }
         .box-1 img{
         width:100px;
         height:50px;
         background-color:white;
         border-radius:10px;
         }
         .box-2 img{
         width:100px;
         height:50px;
         background-color:white;
         border-radius:10px;
         }
         .img-container{
         display: grid;
         justify-content: space-around;
         grid-template-columns: repeat(2,1fr);
         grid-gap: 1rem;
         padding-left :1rem;
         padding-right: 1rem ;
         padding-bottom: 1rem;
         }
         .box-1 img:hover{
         transform: scale(1.1); 
         }
         .box-2 img:hover{
         transform: scale(1.1); 
         }
         input[type="submit"] {
         background-color:#FF6000;
         width:200px;
         height:50px;
         border:none;
         outline:none;
         border-radius:10px;
         font-weight:bold;
         font-size:bolder;
         color:white;
         }
         input[type="submit"]:hover {
         transform: scale(1.1); 
         }
        
         .showPass{
         color:white;
         text-align:right;
         }
         .showPass:hover{
         transform:scale(1.1);
         }
         .hero_content_img img{
             width:30rem;
             height:20rem;
             border-radius:10px;
             }
             
           @media (max-width:480px){
                 .hero_content_img img{
             width:20rem;
             height:19rem;
             border-radius:10px;
             }
               
          }
      </style>
   </head>
   <body>
      </style>
      </head>
      <body>
      
         <section id="hero_content">
            <form class="" action="" method="post" autocomplete="off">
               <div class="login_content" data-ios:"fade-left">
                   <div class="hero_content_img">
                       <img src="forgot_password.png">
                   </div>  
               <h1>Forgot Password?</h1>
         
            
               <div class="input_container">
                  <label for="email" style="color:white;">Enter your Email:</label>
                  <div class="icon_input">
                     <i class="fas fa-envelope"></i>
           
                       <input type="email" id="email" name="email" placeholder="Your Email" required>
                  </div>
               </div>
             
               <button type="submit"  name="submit"  onclick="validate()">Submit</button>
               </div>
            </form>
         </section>
         <script>
            function show_password(){
                var x=document.getElementById("password")
                if(x.type==="password"){
                    x.type="text";
                }
                else{
                    x.type="password";
                    
                }
                
            }
         </script>
         <script>
            function validate(){
                 var regemail=document.getElementById("email").value;
                   if(!regemail){
                           alert("please enter email");
                            document.getElementById('email').focus();
                      }
                        if(!passwordTest){
                            alert("please enter password");
                            document.getElementById('password').focus();
                      }
            
                      else{
                          
                          return true;
                       }
            }
         </script>
        
   </body>
</html>
